# Generated by Django 5.1 on 2024-09-16 07:46

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.PositiveIntegerField(choices=[(0, 'Admin'), (1, 'Moderator'), (2, 'Moderator')], editable=False, verbose_name='Role identifier')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='person.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Person role',
                'verbose_name_plural': 'Person roles',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('person', 'role'), name='unique_personrole')],
            },
        ),
    ]
