# Generated by Django 5.1 on 2024-09-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_personrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='saved_playlists',
        ),
    ]
