# Generated by Django 5.1 on 2024-09-30 07:15

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_albumtrack_album_tracks_playlisttrack_and_more'),
        ('person', '0003_remove_person_saved_playlists'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlaylist',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='person.person', verbose_name='Owner')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='music.playlist', verbose_name='Playlist')),
            ],
            options={
                'verbose_name': 'Saved playlist',
                'verbose_name_plural': 'Saved playlists',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='saved_playlists',
            field=models.ManyToManyField(through='person.SavedPlaylist', to='music.playlist'),
        ),
        migrations.AddConstraint(
            model_name='savedplaylist',
            constraint=models.UniqueConstraint(fields=('owner', 'playlist'), name='unique_savedplaylist'),
        ),
    ]
