# Generated by Django 5.1 on 2024-09-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_savedplaylist_person_saved_playlists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personrole',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedplaylist',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
