# Generated by Django 5.1 on 2024-10-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_person_is_removed_personrole_is_removed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='personrole',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='savedplaylist',
            name='is_removed',
        ),
    ]
