repos:
  - repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
      - id: flake8
        language_version: python3.12.5
        entry: flake8 .
  - repo: https://github.com/psf/black
    rev: '24.8.0'
    hooks:
      - id: black
        language_version: python3.12.5
        entry: black .
        args: ["--check"]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        entry: isort .
        args: ["--check"]
        pass_filenames: false