# Generated by Django 5.1 on 2024-09-09 17:07

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Avatar')),
                ('summary', models.CharField(blank=True, null=True, verbose_name='Summary')),
                ('public_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Public email')),
                ('saved_playlists', models.ManyToManyField(related_name='followers', related_query_name='follower', to='music.playlist')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='PlaylistComment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='social.person', verbose_name='Author')),
                ('target', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='music.playlist', verbose_name='Playlist')),
            ],
            options={
                'verbose_name': 'Playlist comment',
                'verbose_name_plural': 'Playlist comments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackComment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='social.person', verbose_name='Author')),
                ('target', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='music.track', verbose_name='Track')),
            ],
            options={
                'verbose_name': 'Track comment',
                'verbose_name_plural': 'Track comments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistLike',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liked_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='social.person', verbose_name='Liked by')),
                ('target', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='music.playlist', verbose_name='Playlist')),
            ],
            options={
                'verbose_name': 'Playlist like',
                'verbose_name_plural': 'Playlist likes',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('liked_by', 'target'), name='unique_playlistlike')],
            },
        ),
        migrations.CreateModel(
            name='TrackLike',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liked_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='social.person', verbose_name='Liked by')),
                ('target', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='music.track', verbose_name='Track')),
            ],
            options={
                'verbose_name': 'Track like',
                'verbose_name_plural': 'Track likes',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('liked_by', 'target'), name='unique_tracklike')],
            },
        ),
    ]
