# Generated by Django 5.1 on 2024-09-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playlistlike',
            name='unique_playlistlike',
        ),
        migrations.RemoveConstraint(
            model_name='tracklike',
            name='unique_tracklike',
        ),
        migrations.RemoveField(
            model_name='playlistcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='playlistlike',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='trackcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tracklike',
            name='liked_by',
        ),
    ]
