# Generated by Django 5.1 on 2024-09-09 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_owner_playlist_owner_track_owner'),
        ('social', '0002_remove_playlistlike_unique_playlistlike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistcomment',
            name='owner',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, to='social.person', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='playlistlike',
            name='owner',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, to='social.person', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='trackcomment',
            name='owner',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, to='social.person', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='tracklike',
            name='owner',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, to='social.person', verbose_name='Owner'),
        ),
        migrations.AddConstraint(
            model_name='playlistlike',
            constraint=models.UniqueConstraint(fields=('owner', 'target'), name='unique_playlistlike'),
        ),
        migrations.AddConstraint(
            model_name='tracklike',
            constraint=models.UniqueConstraint(fields=('owner', 'target'), name='unique_tracklike'),
        ),
    ]
