# Generated by Django 5.1 on 2024-09-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_playlistcomment_subject_trackcomment_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcomment',
            name='subject',
            field=models.TextField(verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='playlistcomment',
            name='subject',
            field=models.TextField(verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='subject',
            field=models.TextField(verbose_name='Subject'),
        ),
    ]
