# Generated by Django 5.1 on 2024-09-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_albumcomment_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='subscribers',
            field=models.ManyToManyField(related_query_name='subscriber', to='social.person'),
        ),
    ]
