# Generated by Django 5.1 on 2024-09-13 09:20

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_album_owner_alter_playlist_owner_and_more'),
        ('social', '0007_person_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumLike',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='social.person', verbose_name='Owner')),
                ('target', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='music.album', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Album like',
                'verbose_name_plural': 'Album likes',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('owner', 'target'), name='unique_albumlike')],
            },
        ),
    ]
