# Generated by Django 5.1 on 2024-09-16 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_album_owner_alter_playlist_owner_and_more'),
        ('person', '0001_initial'),
        ('social', '0008_albumlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracklike',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='person.person', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='playlistcomment',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='person.person', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='person.person', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='playlistlike',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='person.person', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='albumcomment',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='person.person', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='albumlike',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='person.person', verbose_name='Owner'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
