# Generated by Django 5.1 on 2024-10-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_like_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='target_type',
            field=models.PositiveIntegerField(choices=[(0, 'Track'), (1, 'Album'), (2, 'Playlist'), (3, 'Comment')], editable=False, verbose_name='Target model type'),
        ),
    ]
