# Generated by Django 5.1 on 2024-10-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_alter_like_target_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="Like",
            name="unique_like",
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
