# Generated by Django 5.1 on 2024-10-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistcomment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='playlistcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='playlistcomment',
            name='target',
        ),
        migrations.RemoveField(
            model_name='trackcomment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trackcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='trackcomment',
            name='target',
        ),
        migrations.DeleteModel(
            name='AlbumComment',
        ),
        migrations.DeleteModel(
            name='PlaylistComment',
        ),
        migrations.DeleteModel(
            name='TrackComment',
        ),
    ]
