# Generated by Django 5.1 on 2024-10-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_remove_playlistcomment_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
