"""
Django settings for kubstu.music-hosting.back project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from split_settings.tools import include

base_settings = [
    "components/app.py",
    "components/base.py",
    "components/cors.py",
    "components/db.py",
    "components/debug.py",
    "components/djoser.py",
    "components/installed_apps.py",
    "components/middleware.py",
    "components/oas3.py",
    "components/rest.py",
    "components/static.py",
    "components/templates.py",
]

include(*base_settings)
