# Generated by Django 5.1 on 2024-09-09 18:41

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_track_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='track',
            name='uploaded_by',
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='Album title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Album description')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release date')),
                ('tracks', models.ManyToManyField(related_name='albums', to='music.track', verbose_name='Tracks')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Playlists',
                'abstract': False,
            },
        ),
    ]
