# Generated by Django 5.1 on 2024-09-09 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_remove_playlist_created_by_remove_track_uploaded_by_and_more'),
        ('social', '0002_remove_playlistlike_unique_playlistlike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, to='social.person', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, to='social.person', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='track',
            name='owner',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, to='social.person', verbose_name='Owner'),
        ),
    ]
