# Generated by Django 5.1 on 2024-09-09 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_owner_playlist_owner_track_owner'),
        ('social', '0004_alter_playlistcomment_owner_alter_playlistlike_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='social.person', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='social.person', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='track',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='social.person', verbose_name='Owner'),
        ),
    ]
