# Generated by Django 5.1 on 2024-09-27 09:16

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_remove_album_tracks_remove_playlist_tracks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='music.album', verbose_name='Album')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='music.track', verbose_name='Track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(related_name='albums', through='music.AlbumTrack', to='music.track', verbose_name='Tracks'),
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='music.playlist', verbose_name='Playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='music.track', verbose_name='Track')),
            ],
            options={
                'verbose_name': 'Playlist track',
                'verbose_name_plural': 'Playlist tracks',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', through='music.PlaylistTrack', to='music.track', verbose_name='Tracks'),
        ),
        migrations.AddConstraint(
            model_name='albumtrack',
            constraint=models.UniqueConstraint(fields=('album', 'track'), name='unique_albumtrack'),
        ),
        migrations.AddConstraint(
            model_name='playlisttrack',
            constraint=models.UniqueConstraint(fields=('playlist', 'track'), name='unique_playlisttrack'),
        ),
    ]
