# Generated by Django 5.1 on 2024-09-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_albumtrack_album_tracks_playlisttrack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='albumtrack',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
