# Generated by Django 5.1 on 2024-10-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_album_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='albumtrack',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='playlisttrack',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='track',
            name='is_removed',
        ),
    ]
