# Generated by Django 5.1 on 2024-10-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_remove_album_is_removed_remove_albumtrack_is_removed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumtrack',
            options={'verbose_name': 'Album track', 'verbose_name_plural': 'Album tracks'},
        ),
        migrations.RemoveConstraint(
            model_name='albumtrack',
            name='unique_albumtrack',
        ),
        migrations.RemoveConstraint(
            model_name='playlisttrack',
            name='unique_playlisttrack',
        ),
        migrations.RenameField(
            model_name='albumtrack',
            old_name='album',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='playlisttrack',
            old_name='playlist',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='albumtrack',
            name='number',
            field=models.PositiveIntegerField(null=True, verbose_name='Number in the list'),
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='number',
            field=models.PositiveIntegerField(null=True, verbose_name='Number in the list'),
        ),
        migrations.AlterField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(through='music.AlbumTrack', to='music.track', verbose_name='Tracks'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(through='music.PlaylistTrack', to='music.track', verbose_name='Tracks'),
        ),
        migrations.AddConstraint(
            model_name='albumtrack',
            constraint=models.UniqueConstraint(fields=('parent', 'track'), name='unique_albumtrack'),
        ),
        migrations.AddConstraint(
            model_name='playlisttrack',
            constraint=models.UniqueConstraint(fields=('parent', 'track'), name='unique_playlisttrack'),
        ),
    ]
