# Generated by Django 5.1 on 2024-10-14 06:16

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0011_album_is_removed_albumtrack_is_removed_and_more'),
        ('person', '0005_person_is_removed_personrole_is_removed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumComment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.TextField(verbose_name='Subject')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='person.person', verbose_name='Owner')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='comments.albumcomment')),
                ('target', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to='music.album', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Album comment',
                'verbose_name_plural': 'Album comments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistComment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.TextField(verbose_name='Subject')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='person.person', verbose_name='Owner')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='comments.playlistcomment')),
                ('target', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to='music.playlist', verbose_name='Playlist')),
            ],
            options={
                'verbose_name': 'Playlist comment',
                'verbose_name_plural': 'Playlist comments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackComment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.TextField(verbose_name='Subject')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='person.person', verbose_name='Owner')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='comments.trackcomment')),
                ('target', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to='music.track', verbose_name='Track')),
            ],
            options={
                'verbose_name': 'Track comment',
                'verbose_name_plural': 'Track comments',
                'abstract': False,
            },
        ),
    ]
