# Generated by Django 5.1 on 2024-10-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumcomment',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='playlistcomment',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='trackcomment',
            name='is_removed',
        ),
    ]
