# Generated by Django 5.1 on 2024-10-29 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_albumcomment_is_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcomment',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Visible'), (1, 'Removed')], default=0, verbose_name='Comment status'),
        ),
        migrations.AddField(
            model_name='playlistcomment',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Visible'), (1, 'Removed')], default=0, verbose_name='Comment status'),
        ),
        migrations.AddField(
            model_name='trackcomment',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Visible'), (1, 'Removed')], default=0, verbose_name='Comment status'),
        ),
        migrations.AlterField(
            model_name='albumcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='comments.albumcomment', verbose_name='Parent comment'),
        ),
        migrations.AlterField(
            model_name='playlistcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='comments.playlistcomment', verbose_name='Parent comment'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='comments.trackcomment', verbose_name='Parent comment'),
        ),
    ]
