# Generated by Django 5.1 on 2024-10-29 11:41

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_albumcomment_status_playlistcomment_status_and_more'),
        ('person', '0006_remove_person_is_removed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistcomment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='playlistcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='playlistcomment',
            name='target',
        ),
        migrations.RemoveField(
            model_name='trackcomment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trackcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='trackcomment',
            name='target',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_id', models.UUIDField(editable=False, verbose_name='Target ID')),
                ('subject', models.TextField(verbose_name='Subject')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Visible'), (1, 'Removed')], default=0, verbose_name='Comment status')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='person.person', verbose_name='Owner')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='comments.comment', verbose_name='Parent comment')),
            ],
            options={
                'verbose_name': 'Commentary',
                'verbose_name_plural': 'Commentaries',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AlbumComment',
        ),
        migrations.DeleteModel(
            name='PlaylistComment',
        ),
        migrations.DeleteModel(
            name='TrackComment',
        ),
    ]
