# Generated by Django 5.1 on 2024-10-14 05:36

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0016_delete_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_id', models.UUIDField(editable=False, verbose_name='Target ID')),
                ('target_type', models.PositiveIntegerField(choices=[(0, 'Track'), (1, 'Album'), (2, 'Playlist'), (3, 'Comment')], editable=False, verbose_name='Target model type')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='person.person', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('owner', 'target_id'), name='unique_like')],
            },
        ),
    ]
