# Generated by Django 5.1 on 2024-10-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_removed',
        ),
    ]
