# Generated by Django 5.1 on 2024-11-01 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0003_remove_like_target_type_like_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype', verbose_name='Content type'),
        ),
    ]
